import React from 'react'
import { CheckCircle2, Download, Plus, ArrowRight, Home, Share2 } from 'lucide-react'
import { motion } from 'framer-motion'
import { jsPDF } from 'jspdf'

const ComplaintSubmitted = ({ t, data, onHome, onTrack }) => {
    const complaintId = data?.id || "CIV-20451"

    const downloadReceipt = () => {
        const doc = new jsPDF()

        // Header
        doc.setFillColor(59, 130, 246)
        doc.rect(0, 0, 210, 40, 'F')
        doc.setTextColor(255, 255, 255)
        doc.setFontSize(24)
        doc.text("nIVaan Official Receipt", 105, 25, { align: 'center' })

        // Body
        doc.setTextColor(0, 0, 0)
        doc.setFontSize(16)
        doc.text("Complaint Details", 20, 60)

        doc.setFontSize(11)
        doc.text(`Reference ID: ${complaintId}`, 20, 75)
        doc.text(`Date Submitted: ${data?.dateSubmitted || new Date().toLocaleDateString()}`, 20, 83)
        doc.text(`Department: ${data?.department || 'N/A'}`, 20, 91)
        doc.text(`Category: ${data?.category || 'N/A'}`, 20, 99)

        doc.setFontSize(12)
        doc.text("Location Information:", 20, 115)
        doc.setFontSize(10)
        doc.text(`Address: ${data?.address || 'Auto-detected'}`, 20, 123, { maxWidth: 170 })
        if (data?.location) {
            doc.text(`Coordinates: ${data.location.lat.toFixed(6)}, ${data.location.lng.toFixed(6)}`, 20, 135)
        }

        doc.setFontSize(12)
        doc.text("Complaint Description:", 20, 150)
        doc.setFontSize(10)
        doc.text(data?.description || 'No description provided', 20, 158, { maxWidth: 170 })

        // Evidence Image
        if (data?.evidence?.photo) {
            try {
                doc.addPage()
                doc.setFontSize(16)
                doc.text("Evidence Image", 20, 20)
                doc.addImage(data.evidence.photo, 'JPEG', 20, 30, 170, 120)
            } catch (e) {
                console.error("Could not add image to PDF", e)
            }
        }

        doc.setDrawColor(200, 200, 200)
        doc.line(20, 270, 190, 270)

        doc.setFontSize(9)
        doc.setTextColor(100, 100, 100)
        doc.text("This is an official document generated by nIVaan Public Service Portal.", 105, 280, { align: 'center' })
        doc.text("For any queries, please visit the portal with your Reference ID.", 105, 285, { align: 'center' })

        doc.save(`nivaan_receipt_${complaintId}.pdf`)
    }

    const shareComplaint = async () => {
        const shareData = {
            title: 'nIVaan Complaint Status',
            text: `I've submitted a complaint on nIVaan portal. Reference ID: ${complaintId}. Track it here!`,
            url: window.location.href
        }

        try {
            if (navigator.share) {
                await navigator.share(shareData)
            } else {
                // Fallback: Copy to clipboard
                await navigator.clipboard.writeText(`${shareData.text} ${shareData.url}`)
                alert('Complaint details copied to clipboard!')
            }
        } catch (err) {
            console.error('Error sharing:', err)
        }
    }

    return (
        <div style={{ minHeight: '100vh', background: '#f8fafc', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '2rem' }}>
            <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                className="glass-card"
                style={{ maxWidth: '480px', width: '100%', padding: '3.5rem 2.5rem', textAlign: 'center', borderRadius: '1.5rem', background: 'white', border: '1px solid #e2e8f0' }}
            >
                <div style={{ display: 'inline-flex', marginBottom: '1.5rem' }}>
                    <div style={{
                        width: '72px',
                        height: '72px',
                        background: '#dcfce7',
                        color: '#166534',
                        borderRadius: '50%',
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center'
                    }}>
                        <CheckCircle2 size={40} />
                    </div>
                </div>

                <h1 style={{ fontSize: '1.75rem', fontWeight: '800', color: '#0f172a', marginBottom: '1rem' }}>Complaint Submitted Successfully!</h1>
                <p style={{ color: '#64748b', fontSize: '1rem', marginBottom: '2rem' }}>
                    REFERENCE ID: <span style={{ color: 'var(--primary)', fontWeight: '800' }}>{complaintId}</span>
                </p>

                <p style={{ fontSize: '0.9rem', color: '#64748b', lineHeight: '1.6', marginBottom: '2.5rem' }}>
                    We have received your report. A confirmation email and SMS have been sent to your registered contact details.
                </p>

                <div style={{ display: 'grid', gap: '1rem' }}>
                    <button
                        className="btn btn-primary"
                        style={{ width: '100%', padding: '1rem', borderRadius: '12px', fontSize: '0.95rem' }}
                        onClick={onTrack}
                    >
                        Track Progress <ArrowRight size={18} style={{ marginLeft: '0.5rem' }} />
                    </button>

                    <div style={{ display: 'flex', gap: '1rem' }}>
                        <button
                            onClick={downloadReceipt}
                            className="btn btn-secondary"
                            style={{ flex: 1, padding: '0.8rem', borderRadius: '12px', fontSize: '0.85rem' }}
                        >
                            <Download size={16} /> Download Receipt
                        </button>
                        <button
                            onClick={shareComplaint}
                            className="btn btn-secondary"
                            style={{ flex: 1, padding: '0.8rem', borderRadius: '12px', fontSize: '0.85rem' }}
                        >
                            <Share2 size={16} /> Share Details
                        </button>
                    </div>

                    <button
                        className="btn btn-secondary"
                        style={{ width: '100%', padding: '0.8rem', borderRadius: '12px', fontSize: '0.85rem', background: '#f1f5f9', border: 'none' }}
                        onClick={onHome}
                    >
                        <Plus size={16} /> Submit Another
                    </button>
                </div>

                <div style={{ marginTop: '3rem', paddingTop: '1.5rem', borderTop: '1px solid #f1f5f9' }}>
                    <button
                        onClick={onHome}
                        style={{ background: 'none', border: 'none', color: '#64748b', fontSize: '0.9rem', fontWeight: '600', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '0.5rem', margin: '0 auto' }}
                    >
                        <Home size={16} /> Back to Dashboard
                    </button>
                </div>
            </motion.div>
        </div>
    )
}

export default ComplaintSubmitted
